apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: likhitha2128/nginx-image:latest
      ports:
        - containerPort: 82
      volumeMounts:
        - name: data-volume
          mountPath: /data/
  volumes:
    - name: data-volume
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 82
      targetPort: 82
      nodePort: 30001   # choose any 30000–32767
