apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
        - name: nginx
          image: likhitha2128/nginx-image:latest
          ports:
            - containerPort: 82
          volumeMounts:
            - name: nginx-data
              mountPath: /data/
      volumes:
        - name: nginx-data
          emptyDir: {} 

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-replicaset-service
spec:
  type: NodePort
  selector:
    app: nginx-rs
  ports:
    - port: 82
      targetPort: 82
      nodePort: 30002
      protocol: TCP
